<?php
declare(strict_types = 1);

use Lemon\Http\Response;

/** @var int $code */

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        <?php echo Response::ERROR_STATUS_CODES[$code] ?></title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap');
        
        * {
            font-family: 'Roboto', sans-serif;
        }
    </style>
</head>
<body style="min-height: 100vh; margin: 10%; align-items: center; display: flex">
    <div style="display: block;">
        <?php echo $code ?>
        <hr>
        <?php echo Response::ERROR_STATUS_CODES[$code] ?>
    </div>
</body>
</html>
