<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $message ?></title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap');
        
        * {
            font-family: 'Roboto', sans-serif;
        }
    </style>
</head>
<body style="min-height: 100vh; margin: 10%; align-items: center; display: flex">
    <div style="display: block;">
        <?php echo $code ?>
        <hr>
        <?php echo $message ?>
    </div>
</body>
</html>
